apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
spec:
  hostPID: true
  restartPolicy: Never
  containers:
    - name: cpp
      image: gcc:4.9
      imagePullPolicy: Always
      securityContext:
        privileged: true
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
      env:
        - name: SHELL_ENV_DISPLAY
          value: production system
    - name: debugger
      image: docker-hub.sandstorm.de/public-containers/ebpf-tracer:latest
      imagePullPolicy: Always
      securityContext:
        privileged: true
      env:
        - name: SHELL_ENV_DISPLAY
          value: production system
      volumeMounts:
        - name: src-volume
          mountPath: /usr/src
  volumes:
    - name: src-volume
      hostPath:
        path: /usr/src
        type: Directory
